language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
stages:
  - compile
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      script: npm test
    - stage: compile
      script: npm run build
    - stage: deploy frontend
      script: skip
      deploy: &heroku
        provider: heroku
        app: webapps05
        api-key: $HEROKU_KEY
      on:
        branch: master
    
